name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    env:
      CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
      CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
      CF_PAGES_PROJECT_NAME: ${{ secrets.CF_PAGES_PROJECT_NAME || 'mbgifts' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Build with next-on-pages
        run: npx @cloudflare/next-on-pages

      - name: Deploy to Cloudflare Pages
        run: |
          npx wrangler pages deploy .vercel/output/static             --project-name="${{ env.CF_PAGES_PROJECT_NAME }}"             --branch="main"
